services:
  container-swoole:
    container_name: container-swoole
    image: phpswoole/swoole:php8.3
    volumes:
      - ./swoole-example:/var/www
    ports:
      - 8080:8080
    command: "php service.php"

  container-fpm:
    container_name: container-fpm
    image: php:8.3.8-fpm
    volumes:
      - ./fpm-example:/var/www
    ports:
      - 8081:8080
    command: "tail -f /dev/null"
