services:
  container-swoole:
    container_name: container-swoole
    image: phpswoole/swoole:php8.3
    volumes:
      - ./swoole-example:/var/www
    ports:
      - 8080:8080
    mem_limit: 16m
    cpus: 0.01 # 62,5 MHz
    command: "php service.php"
